# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  release:
    types: [created, published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 16
      - run: npm ci
      - run: script/build
      - run: npm exec -- prettier --check src
      - name: Create tarball
        run: |
          tar -czf /tmp/bruce-esp-web-tools.tgz --exclude='.git' --exclude='node_modules' .
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/bruce-esp-web-tools.tgz
          asset_name: bruce-esp-web-tools.tgz
          asset_content_type: application/gzip
      - name: Publish release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              draft: false
            });
